apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name:  {{ .Values.name }}
  namespace:  {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name:  {{ .Values.name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        args: ["--dbpath","/data/db"]
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  {{ .Values.name }}-creds
              key: password
        volumeMounts:
        - name:  {{ .Values.name }}-data-dir
          mountPath: "/data/db"
      volumes:
      - name: {{ .Values.name }}-data-dir
        persistentVolumeClaim:
          claimName: "{{ .Values.name }}-data"