apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ .Values.name }}
  name:  {{ .Values.name }}-nodeport-svc
  namespace:  {{ .Values.name }}
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: {{ .Values.nodeport }}
  selector:
    app:  {{ .Values.name }}
  type: NodePort