apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ .Values.name }}-data-pv
  namespace:  {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/{{ .Values.name }}