apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ .Values.name }}
  name:  {{ .Values.name }}-cs-nodeport-svc
  namespace:  {{ .Values.name }}
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
    nodePort: {{ .Values.nodeportcs }}
  selector:
    app:  {{ .Values.name }}
  type: NodePort